server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    config:
      enabled: true
      uri: ${SPRING_CLOUD_CONFIG_URI:http://config-server:8888}
      fail-fast: true
      retry:
        max-attempts: 6
        max-interval: 2000
        initial-interval: 1000
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**, /api/v1/auth/**
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/v1/accounts/**
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/api/v1/transactions/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        all: true
      slo:
        http.server.requests: 50ms, 100ms, 200ms, 500ms
