apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-config
data:
  SPRING_CLOUD_CONFIG_URI: http://config-server:8888
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bankdb
  SPRING_DATASOURCE_USERNAME: postgres
  LOGGING_LEVEL_ROOT: INFO
